# Generated by Django 5.1.1 on 2025-08-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-updated_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newstopic',
            options={'ordering': ['id'], 'verbose_name': 'Тема новостей', 'verbose_name_plural': 'Темы новостей'},
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.AlterModelTable(
            name='newstopic',
            table='news_topic',
        ),
    ]
