# Generated by Django 5.1.1 on 2025-08-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_news_options_alter_newstopic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
