# Generated by Django 5.1.1 on 2025-08-23 05:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title', unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
