# Generated by Django 5.1.1 on 2025-08-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_news_updated_at_news_updated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-updated_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newstopic',
            options={'ordering': ['id'], 'verbose_name': 'Тема новостей', 'verbose_name_plural': 'Темы новостей'},
        ),
    ]
