# Generated by Django 5.1.1 on 2025-08-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_options_alter_newstopic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newstopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newstopic', verbose_name='Темы'),
        ),
    ]
