# Generated by Django 5.1.1 on 2025-08-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_newstopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
